### ISSUE TITLE
Program reaches too many DB-connections and crashes

### ISSUE THREAD

**Issue by SvenskaBarnet** [SvenskaBarnet/real-time-horror-group3#105]
should we up the max amount of allowed connections or should we write code that closes connections after use?

**Comment by SvenskaBarnet** [comment]
Unhandled exception. Npgsql.NpgsqlException (0x80004005): The connection pool has been exhausted, either raise 'Max Pool Size' (currently 100) or 'Timeout' (currently 15 seconds) in your connection string.

**Comment by Clone888** [comment]
Unhandled exception. Npgsql.PostgresException (0x80004005): 53300: sorry, too many clients already
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
