### ISSUE TITLE
Change intro story

### ISSUE THREAD

**Issue by Clone888** [SvenskaBarnet/real-time-horror-group3#152]
Ändra så att introt stämmer överens med tid som ges och vad som händer. 
Kanske korta ner den något?

**Comment by viggosjostrom** [comment]
Förslag på ny introstory:
You stand tired in your kitchen reheating some leftover noodles from yesterday.
Suddenly you hear some strange banging noises coming from outside of the house
Looking out the kitchen window you see two dark masked figures trying to break your garage door.
OMG! They'll sure be going for the house next!
You need to keep it secure as long as you can by checking
every room ('kitchen', 'hallway', 'living room') for any open entry point.
But be careful about your steps along the way, strange things could happen..";

**Comment by Clone888** [comment]
Behövs där text om hur mycket tid som spelaren får?
